"""Change lab_number column in labs table

Revision ID: 55353db27dc7
Revises: 
Create Date: 2024-09-25 09:14:22.515107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55353db27dc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.alter_column('lab_number',
               existing_type=mysql.INTEGER(),
               nullable=False,
               unique=True)
        batch_op.create_unique_constraint(None, ['lab_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('lab_number',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
