"""Added location and department colums to lab table.

Revision ID: 9652aa152b2f
Revises: 
Create Date: 2024-09-22 11:52:40.071598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9652aa152b2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_column('department')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
