"""empty message

Revision ID: 0486a33674c0
Revises: bced9b2bc642
Create Date: 2024-09-27 08:45:17.448279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0486a33674c0'
down_revision = 'bced9b2bc642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guidance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guidance', schema=None) as batch_op:
        batch_op.drop_column('topic')

    # ### end Alembic commands ###
