"""Add is_delete column to guidance table

Revision ID: 0a98477975db
Revises: 55353db27dc7
Create Date: 2024-09-25 09:46:38.907018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a98477975db'
down_revision = '55353db27dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guidance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_delete', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guidance', schema=None) as batch_op:
        batch_op.drop_column('is_delete')

    # ### end Alembic commands ###
