"""Add the colunm x, y, point_id to intro and two img colum to ssi_lab

Revision ID: 286a5f72da7a
Revises: a6e6322fcacd
Create Date: 2024-10-08 18:46:41.999074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286a5f72da7a'
down_revision = 'a6e6322fcacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('x', sa.Float(precision=53), nullable=True))
        batch_op.add_column(sa.Column('y', sa.Float(precision=53), nullable=True))

    with op.batch_alter_table('ssi_labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_segmentation', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('img_total', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssi_labs', schema=None) as batch_op:
        batch_op.drop_column('img_total')
        batch_op.drop_column('img_segmentation')

    with op.batch_alter_table('intro', schema=None) as batch_op:
        batch_op.drop_column('y')
        batch_op.drop_column('x')
        batch_op.drop_column('point_id')

    # ### end Alembic commands ###
