"""Add the table ssi_labs and table intro

Revision ID: 33407b3a2dea
Revises: 0a98477975db
Create Date: 2024-09-25 16:29:58.064616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33407b3a2dea'
down_revision = '0a98477975db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssi_labs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lab_name', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('lab_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_name'),
    sa.UniqueConstraint('lab_number')
    )
    op.create_table('intro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.BigInteger(), nullable=False),
    sa.Column('time_line', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.String(length=200), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intro')
    op.drop_table('ssi_labs')
    # ### end Alembic commands ###
