"""empty message

Revision ID: a6e6322fcacd
Revises: 0486a33674c0
Create Date: 2024-09-27 15:23:03.594393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6e6322fcacd'
down_revision = '0486a33674c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('time_line')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_line', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
