"""Add the ico_path, room_num, introduction, article to table ssi_lab

Revision ID: a787eb7f323d
Revises: 286a5f72da7a
Create Date: 2024-10-09 14:23:55.745332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a787eb7f323d'
down_revision = '286a5f72da7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intro', schema=None) as batch_op:
        batch_op.alter_column('x',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=53),
               existing_nullable=True)
        batch_op.alter_column('y',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('ssi_labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ico_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('room_num', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('introduction', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('article', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssi_labs', schema=None) as batch_op:
        batch_op.drop_column('article')
        batch_op.drop_column('introduction')
        batch_op.drop_column('room_num')
        batch_op.drop_column('ico_path')

    with op.batch_alter_table('intro', schema=None) as batch_op:
        batch_op.alter_column('y',
               existing_type=sa.Float(precision=53),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('x',
               existing_type=sa.Float(precision=53),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    # ### end Alembic commands ###
