"""Changed the table guidances and intro

Revision ID: bced9b2bc642
Revises: ecd0c5915817
Create Date: 2024-09-26 10:17:48.083822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bced9b2bc642'
down_revision = 'ecd0c5915817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guidance', schema=None) as batch_op:
        batch_op.alter_column('audio_path',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('is_delete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'labs', ['lab_number'], ['lab_number'])
        batch_op.drop_column('lab_id')

    with op.batch_alter_table('intro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_number', sa.Integer(), nullable=False))
        batch_op.drop_constraint('intro_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'labs', ['lab_number'], ['lab_number'])
        batch_op.drop_column('lab_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_id', mysql.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('intro_ibfk_1', 'labs', ['lab_id'], ['id'])
        batch_op.drop_column('lab_number')

    with op.batch_alter_table('guidance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_id', mysql.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('is_delete',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
        batch_op.alter_column('audio_path',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
