"""Changed the nullable property of the create_time and update_time fields in the ssi_labs table

Revision ID: ecd0c5915817
Revises: 33407b3a2dea
Create Date: 2024-09-25 16:35:01.970197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecd0c5915817'
down_revision = '33407b3a2dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssi_labs', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssi_labs', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
